cache:
  directories:
  - $HOME/.m2

matrix:
  include:
  - os: windows
    language: bash
    before_install:
#    - git clone https://github.com/portapps/portapps ${TRAVIS_BUILD_DIR}/../portapps
#    - source ${TRAVIS_BUILD_DIR}/../portapps/.travis/prepare.sh
#    - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/java.sh
    - choco install jdk8
    - export JAVA_HOME="c/Program\ Files/Java/jdk1.8.0_211"
    - export PATH=$PATH:$JAVA_HOME/bin
    - choco install maven
  - os: linux
    language: java
    dist: trusty
    jdk: openjdk8
  - os: linux
    language: java
    dist: trusty
    jdk: oraclejdk8
  - os: osx
    language: java
    osx_image: xcode9.3 # Further versions use jdk 10+
  - os: osx
    language: java
    osx_image: xcode10

install:
- mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=${TRAVIS_BUILD_DIR}/lib/org.RDKit.jar -DgroupId=org.rdkit -DartifactId=rdkit -Dversion=1.0.0 -Dpackaging=jar
- mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=${TRAVIS_BUILD_DIR}/lib/org.RDKitDoc.jar -DgroupId=org.rdkit -DartifactId=rdkit-doc -Dversion=1.0.0 -Dpackaging=jar

script: mvn -e test

notifications:
  email: false