version: '3'

services:
  neo4j-test:
    image: neo4j:latest
    ports:
      - "7474:7474" # http
      - "7473:7473" # https
      - "7687:7687" # bolt
    volumes:
#      - "./neo4j-temp/data/:/data"
#      - "./neo4j-temp/logs/:/logs"
#      - "./neo4j-temp/import/:/var/lib/neo4j/import"
#      - "./neo4j-temp/plugins/:/plugins"
      - data:/data
      - logs:/logs
      - import:/var/lib/neo4j/import
      - plugins:/plugins
    environment:
      NEO4J_AUTH: "neo4j/test"

volumes:
  data:
  logs:
  import:
  plugins: